source "https://rubygems.org"
gem "sinatra"
gem "sinatra-contrib"

gem "rspec"
gem "rack"
gem "rack-test"
gem "pry"
gem "guard"
gem "guard-rspec"



#post "/memory" do
#	memoria = Memory.new
#	memoria.add_memory "save_result", params[:operation_finish]
#	memoria.get_memory
#end
